name: Continuous Integration

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-rust:
    uses: ./.github/workflows/build-rust.yml

  build-csharp:
    needs: [build-rust]
    uses: ./.github/workflows/build-csharp.yml
